version: 2

multi-ecosystem-groups:
  python:
    schedule:
      interval: "daily"

updates:
# Python packages - Root directory
- package-ecosystem: "pip"
  directory: "/"
  multi-ecosystem-group: python
  patterns: ["*"]
- package-ecosystem: "uv"
  directory: "/"
  multi-ecosystem-group: python
  patterns: ["*"]

# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"