[project]
name = "CostNav"
version = "0.1.0"
description = "A benchmark for navigation with cost estimation"
readme = "README.md"
requires-python = ">=3.10"

[tool.ruff]
line-length = 119
target-version = "py310"
exclude = ["third_party"]

[tool.ruff.lint]
ignore = ["E402"]
